name: Deploy to Production
on:
  push:
    branches:
      - main
jobs:
  test-on-staging:
    runs-on: ubuntu-latest
    steps:
      - id: ssh
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.DEV_SSH_HOST }}
          SSH_PORT: ${{ secrets.DEV_SSH_PORT }}
          SSH_USER: ${{ secrets.DEV_SSH_USER }}
          SSH_KEY: ${{ secrets.DEV_SSH_KEY }}
      - run: ssh ${{ steps.ssh.outputs.SERVER }} "cd /ci && npx cypress run --browser chrome --spec 'cypress/e2e/mikiya_ogura*.cy.js'"

  deploy-to-production:
    needs: test-on-staging
    runs-on: ubuntu-latest
    steps:
      - id: ssh
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.DEV_SSH_HOST2 }}
          SSH_PORT: ${{ secrets.DEV_SSH_PORT }}
          SSH_USER: ${{ secrets.DEV_SSH_USER }}
          SSH_KEY: ${{ secrets.DEV_SSH_KEY2 }}
      - run: ssh ${{ steps.ssh.outputs.SERVER }} bash /app/mikiya_ogura/deploy.sh mikiya_ogura
